# Generated by Django 3.2.5 on 2021-10-10 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.TextField()),
                ('quiz_type', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=20)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.TextField()),
                ('option_type', models.CharField(max_length=20)),
                ('ans', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionmodel')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmodel')),
            ],
        ),
    ]
