# Generated by Django 3.2.5 on 2021-08-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_value1', models.CharField(blank=True, max_length=200, null=True)),
                ('option_value2', models.CharField(blank=True, max_length=200, null=True)),
                ('option_value3', models.CharField(blank=True, max_length=200, null=True)),
                ('option_value4', models.CharField(blank=True, max_length=200, null=True)),
                ('option_value5', models.CharField(blank=True, max_length=200, null=True)),
                ('optionThemeStyleCss', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Total_quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.TextField()),
                ('inner_css', models.CharField(blank=True, max_length=200, null=True)),
                ('outer_css', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('quest_str', models.TextField()),
                ('option_type', models.CharField(max_length=200)),
                ('questionThemeStyleCss', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateField()),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.options')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.total_quiz')),
            ],
        ),
    ]
