# Generated by Django 3.2.5 on 2021-09-04 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions_table',
            old_name='options',
            new_name='option_id',
        ),
        migrations.AlterField(
            model_name='total_quiz',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
