# Generated by Django 3.2.5 on 2021-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionmodel',
            name='ans',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='ans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
