# Generated by Django 3.2.5 on 2021-09-04 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210905_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_table',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
