# Generated by Django 3.2.5 on 2021-09-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questions_table_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='correct_option',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='quiz_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='quiz.total_quiz'),
            preserve_default=False,
        ),
    ]
